name: Debug LVH

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Debug environment
      run: |
        echo "=== System info ==="
        uname -a
        echo "=== CPU info ==="
        lscpu | grep -E "Architecture|CPU\(s\)|Model name"
        echo "=== Memory ==="
        free -h
        echo "=== Disk space ==="
        df -h
    
    - name: Install LVH
      run: |
        echo "=== Installing LVH ==="
        go install github.com/cilium/little-vm-helper/cmd/lvh@latest
        echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
        export PATH="$(go env GOPATH)/bin:$PATH"
        echo "=== LVH location ==="
        which lvh || echo "lvh not found in PATH"
        echo "=== Go env ==="
        go env GOPATH
        ls -la $(go env GOPATH)/bin/ || true
    
    - name: Test LVH commands
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        echo "=== LVH help ==="
        $(go env GOPATH)/bin/lvh --help || echo "Failed to get help"
        echo "=== LVH kernels help ==="
        $(go env GOPATH)/bin/lvh kernels --help || echo "Failed to get kernels help"
    
    - name: Try to pull a kernel
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        echo "=== Pulling 5.15 kernel ==="
        $(go env GOPATH)/bin/lvh kernels pull 5.15-main || {
          echo "Failed to pull kernel, trying with verbose"
          $(go env GOPATH)/bin/lvh kernels pull 5.15-main -v || echo "Still failed"
        }
        echo "=== Check kernel location ==="
        find $HOME -name "bzImage" -type f 2>/dev/null | head -10 || echo "No kernel images found"
        echo "=== Check .cache directory ==="
        ls -la $HOME/.cache/lvh/kernels/ 2>/dev/null || echo "No .cache/lvh/kernels directory"
    
    - name: Download and test VM image
      run: |
        echo "=== Checking available VM images ==="
        curl -s https://api.github.com/repos/cilium/little-vm-helper/releases/latest | grep -E "browser_download_url.*qcow2" || echo "No qcow2 in latest"
        
        echo "=== Downloading VM image from older release ==="
        # Try v0.0.12 which we know has the image
        wget -O base.qcow2 https://github.com/cilium/little-vm-helper/releases/download/v0.0.12/base.qcow2
        ls -lh base.qcow2
    
    - name: Test QEMU
      run: |
        echo "=== Installing QEMU ==="
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86
        echo "=== QEMU version ==="
        qemu-system-x86_64 --version
        echo "=== Test QEMU ==="
        timeout 5 qemu-system-x86_64 -version || true