name: Find LVH Resources

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  find-resources:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install LVH
      run: |
        go install github.com/cilium/little-vm-helper/cmd/lvh@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Pull kernel and find location
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        echo "=== Pulling kernel ==="
        lvh kernels pull 5.10-main
        
        echo "=== Find all bzImage files ==="
        find ~ -name "bzImage" -type f 2>/dev/null || echo "No bzImage found in home"
        
        echo "=== Check standard locations ==="
        ls -la ~/.local/share/lvh/ 2>/dev/null || echo "No ~/.local/share/lvh"
        ls -la ~/.cache/lvh/ 2>/dev/null || echo "No ~/.cache/lvh"
        ls -la ~/lvh/ 2>/dev/null || echo "No ~/lvh"
        
        echo "=== Find any lvh directories ==="
        find ~ -name "*lvh*" -type d 2>/dev/null | head -20
    
    - name: Check all LVH releases for images
      run: |
        echo "=== Checking LVH releases for VM images ==="
        for version in v0.0.18 v0.0.17 v0.0.16 v0.0.15 v0.0.14 v0.0.13 v0.0.12 v0.0.11 v0.0.10; do
          echo "Checking $version..."
          curl -s https://api.github.com/repos/cilium/little-vm-helper/releases/tags/$version | \
            jq -r '.assets[].browser_download_url' | grep -E "(qcow2|img)" || echo "  No VM images"
        done
    
    - name: Try LVH images build
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        echo "=== Create example config ==="
        lvh images example-config || echo "Failed to create example config"
        
        echo "=== Check images command ==="
        lvh images --help