name: Summary Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-everything:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test 1 - BPF Compilation
      run: |
        echo "=== TEST 1: BPF Compilation ==="
        sudo apt-get update && sudo apt-get install -y clang-15
        cd src/bpf
        clang-15 -O2 -g -target bpf -c minimal.c -o minimal.o
        ls -la minimal.o
        echo "✅ BPF compilation works"
    
    - name: Test 2 - BPF Loading
      run: |
        echo "=== TEST 2: BPF Loading ==="
        sudo apt-get install -y bpftool
        sudo bpftool prog load src/bpf/minimal.o /sys/fs/bpf/test
        sudo bpftool prog show
        sudo rm -f /sys/fs/bpf/test
        echo "✅ BPF loading works"
    
    - name: Test 3 - LVH Installation
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Test 3 continued
      run: |
        echo "=== TEST 3: LVH Installation ==="
        go install github.com/cilium/little-vm-helper/cmd/lvh@latest
        export PATH="$(go env GOPATH)/bin:$PATH"
        lvh version
        echo "✅ LVH installation works"
    
    - name: Test 4 - Kernel Pull
      run: |
        echo "=== TEST 4: Kernel Pull ==="
        export PATH="$(go env GOPATH)/bin:$PATH"
        lvh kernels pull 5.10-main
        # Find where kernel was stored
        find ~ -name "*bzImage*" -type f 2>/dev/null | grep -v ".cache/go-build" | head -5
        echo "✅ Kernel pull works (but location unclear)"
    
    - name: Test 5 - Check OCI Images
      run: |
        echo "=== TEST 5: OCI Images ==="
        # Check if the documented OCI images exist
        docker manifest inspect quay.io/lvh-images/root-images:main || echo "❌ Root image not found"
        docker manifest inspect quay.io/lvh-images/kernel-images:5.10-main || echo "❌ Kernel image not found"
        
        # Try alternative registries
        echo "Checking alternative locations..."
        docker manifest inspect ghcr.io/cilium/little-vm-helper-images:main 2>/dev/null || echo "Not on GitHub"
        docker manifest inspect docker.io/cilium/little-vm-helper-images:main 2>/dev/null || echo "Not on Docker Hub"
    
    - name: Summary
      run: |
        echo "=== SUMMARY ==="
        echo "✅ BPF compilation and loading work"
        echo "✅ LVH installs and runs"
        echo "✅ Kernel pull command works"
        echo "❓ VM images need to be built locally or found in correct registry"
        echo "❓ Kernel storage location needs investigation"