name: Test Without VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-kernels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel-version:
          - "5.15-main"
          - "6.1-main"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y clang bpftool
    
    - name: Build BPF
      run: |
        make -C src/bpf minimal.o
    
    - name: Test BPF locally
      run: |
        sudo bpftool prog load src/bpf/minimal.o /sys/fs/bpf/test_${{ matrix.kernel-version }}
        sudo bpftool prog list
        sudo rm -f /sys/fs/bpf/test_${{ matrix.kernel-version }}
    
    - name: Install LVH
      run: |
        go install github.com/cilium/little-vm-helper/cmd/lvh@v0.0.16
        export PATH="$(go env GOPATH)/bin:$PATH"
        lvh version || echo "No version command"
    
    - name: Test kernel pull
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        # Just test that we can pull kernels
        lvh kernels pull ${{ matrix.kernel-version }} || echo "Kernel pull failed"
        # Check what was downloaded
        find $HOME/.cache -name "*bzImage*" -type f 2>/dev/null | head -5 || echo "No kernels found"